"use client";
import {useEffect,useState} from "react";
import {adminSetSeason,loadAdminDashboard} from "@/data/platform";
import {adminUpsertSeasonReward,loadAdminSeasonRewards} from "@/data/season-admin";
import {formatMoney} from "@/core/currency";

const isoLocal=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
const emptyReward={id:"",season_id:"",level_required:5,reward_type:"CASH",title:"",description:"",emoji:"🎁",cash_amount:0,cosmetic_key:"",sort_order:5};
export default function AdminSeasonPage(){
 const[data,setData]=useState<any>(null),[rewards,setRewards]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[form,setForm]=useState<any>({name:"Bad Decisions Club",slug:"bad-decisions-club",subtitle:"Season 1 · Rewarding imaginary financial irresponsibility.",startsAt:isoLocal(new Date()),endsAt:isoLocal(new Date(Date.now()+45*86400000)),active:true});
 const[reward,setReward]=useState<any>(emptyReward);
 const refresh=async()=>{setBusy(true);setError("");try{const[d,r]=await Promise.all([loadAdminDashboard(),loadAdminSeasonRewards()]);setData(d);setRewards(r);const s=(d?.seasons??[])[0];if(s)setForm({name:s.name,slug:s.slug,subtitle:s.subtitle,startsAt:isoLocal(new Date(s.starts_at)),endsAt:isoLocal(new Date(s.ends_at)),active:s.is_active})}catch(e:any){setError(e?.message??"Admin access required")}finally{setBusy(false)}};
 useEffect(()=>{refresh()},[]);
 const save=async()=>{setBusy(true);setError("");try{await adminSetSeason({name:form.name,slug:form.slug,subtitle:form.subtitle,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),active:form.active});await refresh()}catch(e:any){setError(e?.message??"Could not save season")}finally{setBusy(false)}};
 const saveReward=async()=>{setBusy(true);setError("");try{await adminUpsertSeasonReward({...reward,season_id:reward.season_id||(data?.seasons??[])[0]?.id,level_required:Number(reward.level_required),cash_amount:Number(reward.cash_amount)||0,sort_order:Number(reward.sort_order)||Number(reward.level_required)});setReward(emptyReward);await refresh()}catch(e:any){setError(e?.message??"Could not save reward")}finally{setBusy(false)}};
 if(error&&!data)return <main className="adminShell"><section className="adminDenied"><div className="eyebrow">SEASON ADMIN</div><h1>Access denied.</h1><p>{error}</p><a href="/">Back to shop</a></section></main>;
 return <main className="adminShell"><header className="adminTop"><div><a href="/admin" className="creatorBrand">JUST ORDERED</a><span>SEASON</span></div><div className="row"><a className="secondary linkButton" href="/admin">← Admin</a><a className="secondary linkButton" href="/missions">View missions ↗</a></div></header>
  <section className="adminHero"><div><div className="eyebrow light">SEASON CONTROL</div><h1>Run progression without touching code.</h1></div></section>
  {error&&<div className="adminError">{error}</div>}
  <section className="adminGrid"><div className="adminPanel"><h2>Active season</h2><div className="adminForm"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/></label><label>Subtitle<input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><div className="creatorTwo"><label>Starts<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div><label className="publicToggle"><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Season enabled</label><button className="primary" disabled={busy||!form.name||!form.slug} onClick={save}>{busy?"SAVING…":"SAVE SEASON"}</button></div></div>
  <div className="adminPanel"><div className="eyebrow">SEASON HISTORY</div><h2>Configured seasons</h2><div className="adminProductList">{(data?.seasons??[]).map((s:any)=><button key={s.id} onClick={()=>setForm({name:s.name,slug:s.slug,subtitle:s.subtitle,startsAt:isoLocal(new Date(s.starts_at)),endsAt:isoLocal(new Date(s.ends_at)),active:s.is_active})}><div><b>{s.name}</b><small>{s.is_active?"Enabled":"Disabled"} · {new Date(s.starts_at).toLocaleDateString()} → {new Date(s.ends_at).toLocaleDateString()}</small></div></button>)}</div></div></section>

  <section className="adminGrid"><div className="adminPanel"><div className="eyebrow">REWARD EDITOR</div><h2>{reward.id?"Edit reward":"Add season reward"}</h2><div className="adminForm"><label>Season<select value={reward.season_id} onChange={e=>setReward({...reward,season_id:e.target.value})}><option value="">Active season</option>{(data?.seasons??[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="creatorTwo"><label>Level<input type="number" min="1" value={reward.level_required} onChange={e=>setReward({...reward,level_required:Number(e.target.value),sort_order:Number(e.target.value)})}/></label><label>Type<select value={reward.reward_type} onChange={e=>setReward({...reward,reward_type:e.target.value})}><option>CASH</option><option>BADGE</option><option>PROFILE_FRAME</option><option>COLLECTIBLE</option></select></label></div><div className="creatorTwo"><label>Emoji<input value={reward.emoji} onChange={e=>setReward({...reward,emoji:e.target.value})}/></label><label>Cash amount<input type="number" min="0" value={reward.cash_amount} onChange={e=>setReward({...reward,cash_amount:Number(e.target.value)})}/></label></div><label>Title<input value={reward.title} onChange={e=>setReward({...reward,title:e.target.value})}/></label><label>Description<textarea value={reward.description} onChange={e=>setReward({...reward,description:e.target.value})}/></label><label>Cosmetic key<input value={reward.cosmetic_key??""} onChange={e=>setReward({...reward,cosmetic_key:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})} placeholder="frame_midnight_gold"/></label><button className="primary" disabled={busy||!reward.title} onClick={saveReward}>SAVE REWARD</button></div></div>
  <div className="adminPanel"><div className="eyebrow">REWARD TRACK</div><h2>Configured rewards</h2><div className="adminProductList">{rewards.map((r:any)=><button key={r.id} onClick={()=>setReward({...r})}><span>{r.emoji}</span><div><b>Level {r.level_required} · {r.title}</b><small>{r.reward_type}{Number(r.cash_amount)>0?` · ${formatMoney(Number(r.cash_amount))}`:""} · {r.season_name}</small></div></button>)}</div></div></section>
 </main>
}
