"use client";
import {useEffect,useMemo,useState} from "react";
import {adminReviewSubmission,adminSetCategory,adminSetDailyOverride,adminSetReferralSettings,adminUpsertEvent,adminUpsertProduct,adminUpsertSponsor,loadAdminDashboard} from "@/data/platform";
import {formatMoney} from "@/core/currency";

const emptyProduct={id:"",name:"",category:"Food",price:5000,emoji:"✨",description:"",collection_type:"collectible",delivery_minutes:120,is_active:true,is_featured:false,is_popular:false,rating:4.5,review_count:100,keywords:[] as string[]};
const localDate=()=>new Date().toISOString().slice(0,10);

export default function AdminPage(){
 const[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[section,setSection]=useState("products"),[search,setSearch]=useState(""),[product,setProduct]=useState<any>(emptyProduct);
 const[sponsor,setSponsor]=useState<any>({id:null,name:"",url:"",label:"Sponsored by",active:true,category:""});
 const[event,setEvent]=useState<any>({id:null,name:"",slug:"",headline:"",description:"",theme:"default",featured_category:"",sponsor_id:"",starts_at:"",ends_at:"",is_active:true,product_ids:[]});
 const[daily,setDaily]=useState<any>({day:localDate(),temptation:"",almost:"",dream:"",picks:""}),[referral,setReferral]=useState<any>({enabled:true,inviterReward:25000,inviteeReward:10000,milestone3Reward:50000});
 const refresh=async()=>{setBusy(true);setError("");try{setData(await loadAdminDashboard())}catch(e:any){setError(e?.message??"Admin access required")}finally{setBusy(false)}};
 useEffect(()=>{refresh()},[]);useEffect(()=>{const s=data?.referrals?.settings;if(s)setReferral({enabled:!!s.enabled,inviterReward:Number(s.inviter_reward),inviteeReward:Number(s.invitee_reward),milestone3Reward:Number(s.milestone_3_reward)})},[data]);
 const products=data?.products??[],categories=data?.categories??[],submissions=data?.submissions??[],sponsors=data?.sponsors??[],events=data?.events??[],referralStats=data?.referrals??null;
 const filtered=useMemo(()=>products.filter((p:any)=>`${p.name} ${p.category} ${p.id}`.toLowerCase().includes(search.toLowerCase())).slice(0,120),[products,search]);
 const saveProduct=async()=>{setBusy(true);try{await adminUpsertProduct({...product,price:Number(product.price),delivery_minutes:Number(product.delivery_minutes),rating:Number(product.rating),review_count:Number(product.review_count),keywords:Array.isArray(product.keywords)?product.keywords:String(product.keywords||"").split(",").map((x:string)=>x.trim()).filter(Boolean)});setProduct(emptyProduct);await refresh()}catch(e:any){setError(e?.message??"Could not save product")}finally{setBusy(false)}};
 const approve=async(s:any)=>{setBusy(true);try{await adminReviewSubmission(s.id,"APPROVED","Approved for the catalog.",{name:s.name,category:s.category,price:Number(s.suggested_price),emoji:s.emoji,description:s.description,collection_type:"collectible",delivery_minutes:120,is_active:true,is_featured:false,is_popular:false,rating:4.5,review_count:100,keywords:[s.name.toLowerCase(),s.category.toLowerCase()]});await refresh()}catch(e:any){setError(e?.message??"Approval failed")}finally{setBusy(false)}};
 if(error&&!data)return <main className="adminShell"><section className="adminDenied"><div className="eyebrow">JUST ORDERED ADMIN</div><h1>Access denied.</h1><p>{error}</p><a href="/">Back to shop</a></section></main>;
 return <main className="adminShell"><header className="adminTop"><div><a href="/" className="creatorBrand">JUST ORDERED</a><span>ADMIN</span></div><div className="row"><button className="secondary" onClick={refresh}>Refresh</button><a className="secondary linkButton" href="/">View shop ↗</a></div></header>
  <section className="adminHero"><div><div className="eyebrow light">CONTROL CENTER</div><h1>Run the shop without touching GitHub.</h1></div><div className="adminMetrics"><span><b>{products.length}</b> products</span><span><b>{submissions.filter((x:any)=>x.status==="SUBMITTED").length}</b> waiting ideas</span><span><b>{events.filter((x:any)=>x.is_active).length}</b> enabled events</span><span><b>{Number(referralStats?.count??0)}</b> referrals</span></div></section>
  <nav className="adminTabs">{["products","ideas","events","sponsors","daily","referrals","categories"].map(x=><button key={x} className={section===x?"on":""} onClick={()=>setSection(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {error&&<div className="adminError">{error}</div>}{busy&&<div className="adminBusy">Saving changes…</div>}

  {section==="products"&&<section className="adminGrid"><div className="adminPanel"><div className="sectionhead"><h2>{product.id?"Edit product":"Add product"}</h2>{product.id&&<button className="textbtn" onClick={()=>setProduct(emptyProduct)}>New</button>}</div><div className="adminForm">
   <label>ID <input value={product.id} onChange={e=>setProduct({...product,id:e.target.value})} placeholder="auto if empty"/></label><label>Name <input value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/></label>
   <div className="creatorTwo"><label>Category <select value={product.category} onChange={e=>setProduct({...product,category:e.target.value})}>{categories.map((c:any)=><option key={c.name} value={c.name}>{c.display_name}</option>)}</select></label><label>Emoji <input value={product.emoji} onChange={e=>setProduct({...product,emoji:e.target.value})}/></label></div>
   <div className="creatorTwo"><label>Price <input type="number" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/></label><label>Delivery minutes <input type="number" value={product.delivery_minutes} onChange={e=>setProduct({...product,delivery_minutes:e.target.value})}/></label></div>
   <label>Description <textarea value={product.description??""} onChange={e=>setProduct({...product,description:e.target.value})}/></label><label>Keywords <input value={Array.isArray(product.keywords)?product.keywords.join(", "):product.keywords??""} onChange={e=>setProduct({...product,keywords:e.target.value})}/></label>
   <div className="creatorTwo"><label>Rating <input type="number" step=".1" min="1" max="5" value={product.rating} onChange={e=>setProduct({...product,rating:e.target.value})}/></label><label>Review count <input type="number" value={product.review_count} onChange={e=>setProduct({...product,review_count:e.target.value})}/></label></div>
   <div className="adminChecks"><label><input type="checkbox" checked={!!product.is_active} onChange={e=>setProduct({...product,is_active:e.target.checked})}/> Active</label><label><input type="checkbox" checked={!!product.is_featured} onChange={e=>setProduct({...product,is_featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={!!product.is_popular} onChange={e=>setProduct({...product,is_popular:e.target.checked})}/> Popular</label></div>
   <button className="primary" disabled={busy||!product.name||!product.category} onClick={saveProduct}>SAVE PRODUCT</button>
  </div></div><div className="adminPanel"><div className="sectionhead"><h2>Catalog</h2><input className="adminSearch" placeholder="Search 200+ products…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="adminProductList">{filtered.map((p:any)=><button key={p.id} onClick={()=>setProduct({...p})}><span>{p.emoji}</span><div><b>{p.name}</b><small>{p.category} · {formatMoney(Number(p.price))} · {p.is_active?"Active":"Hidden"}</small></div></button>)}</div></div></section>}

  {section==="ideas"&&<section className="adminPanel"><div className="sectionhead"><div><div className="eyebrow">COMMUNITY QUEUE</div><h2>Product ideas</h2></div></div><div className="adminIdeaList">{submissions.length===0?<div className="empty compact"><b>No submissions yet.</b></div>:submissions.map((s:any)=><article key={s.id} className="adminIdea"><div className="submissionEmoji">{s.emoji}</div><div><div className="row wrap"><b>{s.name}</b><span className={`submissionStatus status-${s.status.toLowerCase().replace("_","-")}`}>{s.status.replaceAll("_"," ")}</span></div><p>{s.category} · {formatMoney(Number(s.suggested_price))} · by @{s.submitter}</p><small>{s.description}</small></div><div className="adminIdeaActions">{s.status!=="APPROVED"&&<button className="primary" onClick={()=>approve(s)}>Approve</button>}{s.status!=="REJECTED"&&<button className="secondary" onClick={async()=>{await adminReviewSubmission(s.id,"REJECTED","Not a fit for the catalog right now.");await refresh()}}>Reject</button>}</div></article>)}</div></section>}

  {section==="sponsors"&&<section className="adminGrid"><div className="adminPanel"><h2>Add / edit sponsor</h2><div className="adminForm"><label>Name<input value={sponsor.name} onChange={e=>setSponsor({...sponsor,name:e.target.value})}/></label><label>Website<input value={sponsor.url} onChange={e=>setSponsor({...sponsor,url:e.target.value})}/></label><label>Label<input value={sponsor.label} onChange={e=>setSponsor({...sponsor,label:e.target.value})}/></label><label>Sponsored category<select value={sponsor.category??""} onChange={e=>setSponsor({...sponsor,category:e.target.value})}><option value="">Event only / none</option>{categories.map((c:any)=><option key={c.name} value={c.name}>{c.display_name}</option>)}</select></label><label className="publicToggle"><input type="checkbox" checked={sponsor.active} onChange={e=>setSponsor({...sponsor,active:e.target.checked})}/> Active</label><button className="primary" onClick={async()=>{await adminUpsertSponsor(sponsor);setSponsor({id:null,name:"",url:"",label:"Sponsored by",active:true,category:""});await refresh()}}>SAVE SPONSOR</button></div></div><div className="adminPanel"><h2>Sponsors</h2><div className="adminProductList">{sponsors.map((s:any)=><button key={s.id} onClick={()=>setSponsor({id:s.id,name:s.name,url:s.website_url,label:s.label,active:s.is_active,category:s.category??""})}><div><b>{s.name}</b><small>{s.label} · {s.category||"Event only"} · {s.is_active?"Active":"Disabled"}</small></div></button>)}</div></div></section>}

  {section==="events"&&<section className="adminGrid"><div className="adminPanel"><h2>{event.id?"Edit event":"Create event"}</h2><div className="adminForm"><label>Name<input value={event.name} onChange={e=>setEvent({...event,name:e.target.value})}/></label><label>Slug<input value={event.slug} onChange={e=>setEvent({...event,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/></label><label>Headline<input value={event.headline} onChange={e=>setEvent({...event,headline:e.target.value})}/></label><label>Description<textarea value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/></label><div className="creatorTwo"><label>Featured category<select value={event.featured_category??""} onChange={e=>setEvent({...event,featured_category:e.target.value})}><option value="">None</option>{categories.map((c:any)=><option key={c.name}>{c.name}</option>)}</select></label><label>Theme<input value={event.theme} onChange={e=>setEvent({...event,theme:e.target.value})}/></label></div><label>Sponsor<select value={event.sponsor_id??""} onChange={e=>setEvent({...event,sponsor_id:e.target.value})}><option value="">None</option>{sponsors.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="creatorTwo"><label>Starts<input type="datetime-local" value={event.starts_at?.slice?.(0,16)??event.starts_at} onChange={e=>setEvent({...event,starts_at:e.target.value})}/></label><label>Ends<input type="datetime-local" value={event.ends_at?.slice?.(0,16)??event.ends_at} onChange={e=>setEvent({...event,ends_at:e.target.value})}/></label></div><label>Featured product IDs<input value={Array.isArray(event.product_ids)?event.product_ids.join(", "):event.product_ids??""} onChange={e=>setEvent({...event,product_ids:e.target.value})} placeholder="l1, l3, v8"/></label><label className="publicToggle"><input type="checkbox" checked={!!event.is_active} onChange={e=>setEvent({...event,is_active:e.target.checked})}/> Enabled</label><button className="primary" onClick={async()=>{const p={...event,product_ids:Array.isArray(event.product_ids)?event.product_ids:String(event.product_ids||"").split(",").map(x=>x.trim()).filter(Boolean),starts_at:new Date(event.starts_at).toISOString(),ends_at:new Date(event.ends_at).toISOString()};await adminUpsertEvent(p);await refresh()}}>SAVE EVENT</button></div></div><div className="adminPanel"><h2>Events</h2><div className="adminProductList">{events.map((e:any)=><button key={e.id} onClick={()=>setEvent({...e,product_ids:[]})}><div><b>{e.name}</b><small>{e.featured_category||"Mixed"} · {e.is_active?"Enabled":"Disabled"} · {new Date(e.starts_at).toLocaleDateString()}</small></div></button>)}</div></div></section>}

  {section==="daily"&&<section className="adminPanel narrow"><div className="eyebrow">MANUAL OVERRIDE</div><h2>Daily Shop</h2><p className="muted">Manual values beat event picks; empty fields fall back to the event or automatic algorithm.</p><div className="adminForm"><label>Date<input type="date" value={daily.day} onChange={e=>setDaily({...daily,day:e.target.value})}/></label><label>Temptation product ID<input value={daily.temptation} onChange={e=>setDaily({...daily,temptation:e.target.value})}/></label><label>Almost Affordable product ID<input value={daily.almost} onChange={e=>setDaily({...daily,almost:e.target.value})}/></label><label>Dream product ID<input value={daily.dream} onChange={e=>setDaily({...daily,dream:e.target.value})}/></label><label>Daily pick IDs<input value={daily.picks} onChange={e=>setDaily({...daily,picks:e.target.value})} placeholder="e1, g2, fa6"/></label><button className="primary" onClick={async()=>{await adminSetDailyOverride({...daily,picks:String(daily.picks).split(",").map(x=>x.trim()).filter(Boolean)});await refresh()}}>SAVE DAILY SHOP</button></div></section>}

  {section==="referrals"&&<section className="adminGrid"><div className="adminPanel"><div className="eyebrow">REFERRAL PROGRAM</div><h2>Rewards & campaign</h2><p className="muted">Changes apply to future successful referrals. Existing rewards are never rewritten.</p><div className="adminForm"><label className="publicToggle"><input type="checkbox" checked={!!referral.enabled} onChange={e=>setReferral({...referral,enabled:e.target.checked})}/> Referrals enabled</label><label>Inviter reward<input type="number" min="0" value={referral.inviterReward} onChange={e=>setReferral({...referral,inviterReward:Number(e.target.value)})}/><small>{formatMoney(Number(referral.inviterReward)||0)}</small></label><label>New shopper reward<input type="number" min="0" value={referral.inviteeReward} onChange={e=>setReferral({...referral,inviteeReward:Number(e.target.value)})}/><small>{formatMoney(Number(referral.inviteeReward)||0)}</small></label><label>3-referral milestone bonus<input type="number" min="0" value={referral.milestone3Reward} onChange={e=>setReferral({...referral,milestone3Reward:Number(e.target.value)})}/><small>{formatMoney(Number(referral.milestone3Reward)||0)}</small></label><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await adminSetReferralSettings(referral);await refresh()}catch(e:any){setError(e?.message??"Could not save referral settings")}finally{setBusy(false)}}}>SAVE REFERRAL SETTINGS</button></div></div><div className="adminPanel"><div className="eyebrow">PROGRAM STATS</div><h2>Referral activity</h2><div className="adminReferralStats"><div><span>Successful referrals</span><b>{Number(referralStats?.count??0)}</b></div><div><span>Base rewards issued</span><b>{formatMoney(Number(referralStats?.rewarded??0))}</b></div><div><span>Current inviter reward</span><b>{formatMoney(Number(referral.inviterReward)||0)}</b></div><div><span>Current welcome bonus</span><b>{formatMoney(Number(referral.inviteeReward)||0)}</b></div></div><p className="muted small">A referral is counted only after a new account signs in through a referral link. Self-referrals and repeat claims are rejected server-side.</p></div></section>}

  {section==="categories"&&<section className="adminPanel"><div className="sectionhead"><h2>Categories</h2><span className="muted">Toggle them without deleting products.</span></div><div className="categoryAdmin">{categories.map((c:any)=><article key={c.name}><div><b>{c.display_name}</b><small>{c.name}</small></div><button className={c.is_active?"primary":"secondary"} onClick={async()=>{await adminSetCategory(c.name,c.display_name,!c.is_active,c.sort_order);await refresh()}}>{c.is_active?"Active":"Hidden"}</button></article>)}</div></section>}
 </main>
}
